### ISSUE TITLE
  python 3: ModuleNotFoundError: No module named 'ply'

### ISSUE THREAD

**Issue by andy-d** [elmundio87/terraform_validate#29]
If this is not intended to be python 3 compatible please let me know, I don't see it documented. Otherwise seeing this on pip install:

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/gy/zv2mh58x4hlfj0lzcw6xn9z80000gn/T/pip-build-i71rzntw/pyhcl/setup.py", line 96, in <module>
      "Topic :: Text Processing"
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/andy/repositories/rube/virtualenv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/gy/zv2mh58x4hlfj0lzcw6xn9z80000gn/T/pip-build-i71rzntw/pyhcl/setup.py", line 37, in run
      self.execute(_pre_install, (), msg="Generating parse table...")
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 335, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/util.py", line 301, in execute
      func(*args)
    File "/private/var/folders/gy/zv2mh58x4hlfj0lzcw6xn9z80000gn/T/pip-build-i71rzntw/pyhcl/setup.py", line 30, in _pre_install
      import hcl
    File "/private/var/folders/gy/zv2mh58x4hlfj0lzcw6xn9z80000gn/T/pip-build-i71rzntw/pyhcl/src/hcl/__init__.py", line 1, in <module>
      from .api import dumps, load, loads
    File "/private/var/folders/gy/zv2mh58x4hlfj0lzcw6xn9z80000gn/T/pip-build-i71rzntw/pyhcl/src/hcl/api.py", line 3, in <module>
      from .parser import HclParser
    File "/private/var/folders/gy/zv2mh58x4hlfj0lzcw6xn9z80000gn/T/pip-build-i71rzntw/pyhcl/src/hcl/parser.py", line 5, in <module>
      from .lexer import Lexer
    File "/private/var/folders/gy/zv2mh58x4hlfj0lzcw6xn9z80000gn/T/pip-build-i71rzntw/pyhcl/src/hcl/lexer.py", line 3, in <module>
      import ply.lex as lex
  ModuleNotFoundError: No module named 'ply'
```

**Comment by atward** [comment]
This is an issue with [pyhcl](https://github.com/virtuald/pyhcl) and needs to be raised upstream. I believe there are already a number of issues related to this.
